# Generated by Django 3.1.4 on 2026-05-17 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('quantidadeVagas', models.IntegerField()),
                ('quantidadeSelecionados', models.IntegerField(default=0)),
                ('dataEvento', models.DateField()),
                ('horarioInicio', models.TimeField()),
                ('horarioFim', models.TimeField()),
                ('criadoEm', models.DateTimeField(auto_now_add=True)),
                ('finalizadoEm', models.DateTimeField(blank=True, null=True)),
                ('endereco', models.CharField(max_length=255)),
                ('remuneracao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('cancelado', 'Cancelado'), ('fechado', 'Fechado'), ('finalizado', 'Finalizado')], default='aberto', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='perfis.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_candidatura', models.DateTimeField(auto_now_add=True)),
                ('mensagem_risco', models.TextField(blank=True, null=True)),
                ('confirmou_risco', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('recusado', 'Recusado')], default='pendente', max_length=20)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.freelancer')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.vaga')),
            ],
            options={
                'unique_together': {('freelancer', 'vaga')},
            },
        ),
    ]
