# Generated by Django 3.1.4 on 2026-05-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='vagas/static/img/'),
        ),
    ]
