# Generated by Django 3.1.4 on 2026-06-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_vaga_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatura',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('recusado', 'Recusado'), ('finalizado', 'Finalizado')], default='pendente', max_length=20),
        ),
    ]
