# Generated by Django 3.1.4 on 2026-06-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0003_auto_20260613_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='categoria',
            field=models.CharField(choices=[('garcom', 'Garçom'), ('atendimento', 'Atendimento'), ('limpeza', 'Limpeza'), ('eventos', 'Eventos'), ('marketing', 'Marketing'), ('programacao', 'Programação'), ('designer', 'Designer')], default='atendimento', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaga',
            name='detalhes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
