# Generated by Django 3.1.4 on 2026-06-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0004_auto_20260615_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='categoria',
            field=models.CharField(choices=[('programacao', 'Programação'), ('desenvolvimento_web', 'Desenvolvimento Web'), ('desenvolvimento_mobile', 'Desenvolvimento Mobile'), ('garcom', 'Garçom'), ('atendimento', 'Atendimento'), ('limpeza', 'Limpeza'), ('eventos', 'Eventos'), ('marketing', 'Marketing'), ('vendas', 'Vendas'), ('designer', 'Designer'), ('fotografia', 'Fotografia'), ('social_media', 'Social Media'), ('assistente', 'Assistente'), ('geral', 'Geral')], max_length=50),
        ),
    ]
