# Generated by Django 3.1.4 on 2026-05-17 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('perfis', '0001_initial'),
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliavaga',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.freelancer'),
        ),
        migrations.AddField(
            model_name='avaliavaga',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.vaga'),
        ),
        migrations.AddField(
            model_name='avaliafreelancer',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.empresa'),
        ),
        migrations.AddField(
            model_name='avaliafreelancer',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.freelancer'),
        ),
        migrations.AddField(
            model_name='avaliafreelancer',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.vaga'),
        ),
        migrations.AlterUniqueTogether(
            name='avaliavaga',
            unique_together={('freelancer', 'vaga')},
        ),
        migrations.AlterUniqueTogether(
            name='avaliafreelancer',
            unique_together={('empresa', 'freelancer', 'vaga')},
        ),
    ]
