# Generated by Django 3.1.4 on 2026-05-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeFantasia', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('descricao', models.TextField()),
                ('site', models.URLField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('avaliacao_media', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('experiencia', models.TextField()),
                ('avaliacao_media', models.FloatField(default=0)),
                ('area_atuacao', models.CharField(choices=[('garcom', 'Garçom'), ('seguranca', 'Segurança'), ('barman', 'Barman'), ('fotografo', 'Fotógrafo'), ('outro', 'Outro')], max_length=50)),
            ],
        ),
    ]
