# Generated by Django 3.1.4 on 2026-06-14 01:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_auto_20260516_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='area_atuacao',
        ),
        migrations.AddField(
            model_name='freelancer',
            name='interesses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='avaliacao_media',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='avaliacao_media',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
