# Generated by Django 3.1.4 on 2026-06-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0003_auto_20260613_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='freelancers/'),
        ),
    ]
