# Generated by Django 3.1.4 on 2026-06-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0004_freelancer_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/'),
        ),
    ]
