# Generated by Django 3.1.4 on 2026-06-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
